### ISSUE TITLE
Copy example duplicate twice the items

### ISSUE THREAD

**Issue by ghost** [kristianmandrup/vue2-dragula-demo#10]
the service "copy" duplicate twice the items when copying into another container

I just cloned this repo, npm install and npm run dev > /global, using copy between containers

**Comment by kristianmandrup** [comment]
The key is to use `:key` when rendering lists on vue. I need to update demo to reflect this requirement in Vue since 2.2 I believe? You can also customise the `ModelManager` class as you see fit. Please help improve the demo to work will with latest Vue (2.3?) and make a PR.
Thanks :)

**Comment by kristianmandrup** [comment]
I guess the copy issue is on the model manager. Perhaps try using a Set instead to avoid duplicates. Not sure exactly what the problem is.

**Comment by kristianmandrup** [comment]
Was it due to missing key as required by Vue 2.2+?

**Comment by ghost** [comment]
Yeah it was. I forgot to close the issue
