### ISSUE TITLE
Example code for drag handle?

### ISSUE THREAD

**Issue by truongio** [kristianmandrup/vue2-dragula-demo#13]
Hi,

I'm struggling to grasp how to create a drag handle and it being the only thing that is draggable inside a component. In the demo code available both the handle and the elements themselves are draggable.

**Comment by truongio** [comment]
Managed to solve it like this: 
 
```
 created() {
    const service = Vue.$dragula.$service
    service.options('first-drake', {
      moves: function (el, source, handle, sibling) {
        return handle.classList.contains('drag-handle')
      }
    })
  }
```

**Comment by kristianmandrup** [comment]
Great! You are very welcome to add your solution to the docs, either the Readme or the wiki :)
