### ISSUE TITLE
How to access model data

### ISSUE THREAD

**Issue by dinogit** [kristianmandrup/vue2-dragula-demo#2]
Hi,

I have a repeater and I have passed data in v-dragula.

How to access that data on drop?

`<div class="kanban__rail" v-for="state in kanban"><div class="kanban__railbody" v-dragula="state" service="kanban"></div></div>`

**Comment by kristianmandrup** [comment]
I recommend you look at the demo app and then the `DragHandler` class. If there is no argument being passed with access to the underlying data model, please make a fix and PR. My computer is in for repair.

**Comment by kristianmandrup** [comment]
I recommend you refactor and improve `DragHandler` to pass the `sourceModel` and more in all emits in a way so that you can destructure the arguments you need on the handler (ie event receiver).

`drop: ({model}) => { ... }`

**Comment by kristianmandrup** [comment]
Alternatively extend DragHandler and pass a factory method in plugin options as described

**Comment by kristianmandrup** [comment]
Just updated to use new event model which can be easily destructured (ie passed as options object) as described above and which contain more useful context data such as the underlying model.
Haven't puplished on npm yet, please test - then if all ok, I will publish.

**Comment by dinogit** [comment]
ok, will try and let you know. Thank you for this 😄

**Comment by kristianmandrup** [comment]
from `DragEffects.js`

```js
    service.on({
      removeModel: ({name, el, source, dragIndex, model}) => {
        log('removeModel: ', el, target, dragIndex, model)
      },
      dropModel: ({name, el, source, target, dropIndex, model}) => {
        log('dropModel: ', el, target, dropIndex, model)
      }
      accepts: ({el, target}) => {
        log('accepts: ', el, target)
        return true // target !== document.getElementById(left)
      },
```

`name` is the drake name

**Comment by dinogit** [comment]
I am not sure if I am doing something wrong, but now "el" is empty, so I get error that el.classList is undefined and can't drag and drop.

**Comment by dinogit** [comment]
can you publish this to npm?

**Comment by kristianmandrup** [comment]
Is it working for you? IF you are having problems, just add `{logging: {dragHandler: true}}` to options passed to the plugin (on init) or the named service you are using.

**Comment by dinogit** [comment]
Hi, I am still getting on drop event model empty.

`drop: ({model}) => {
        log('drop model: ', model)
      }` 

returns ''

**Comment by kristianmandrup** [comment]
i managed to fix it and improve the logging a little more as a bonus. Please try again now. 
I also pushed latest working version to npm. The problem was that the directive life cycle handlers work a bit different than in Vue 1. Need to be triggered on `insert` rather than `update`.
I could only figure this out via experimentation... https://vuejs.org/v2/guide/custom-directive.html

Thanks for helping me find this bug.

**Comment by dinogit** [comment]
I have updated npm and now I get:

```
Uncaught TypeError: targetModel.splice is not a function
Uncaught TypeError: _this.sourceModel.splice is not a function
```

**Comment by dinogit** [comment]
with this setup 

```
    console.log('DRAG EFFECTS: created')
    let dragula = this.$dragula
    let service = dragula.createService({
      name: 'kanban',
      drake: {
        copy: false
      }
    });

    let log = console.log;

    service.on({
      removeModel: ({name, el, source, dragIndex, model}) => {
        log('removeModel: ', el, target, dragIndex, model)
      },
      dropModel: ({name, el, source, target, dropIndex, model}) => {
        log('dropModel: ', el, target, dropIndex, model)
      },
      accepts: ({el, target}) => {
        log('accepts: ', el, target)
        return true // target !== document.getElementById(left)
      },
      drag: ({model}) => {
        log('drop model: ', model)
      },
      drop: ({model}) => {
        log('drop model: ', model)
      },
      over: ({el, container}) => {
        log('over: ', el, container)
      },
      out: ({el, container}) => {
        log('out: ', el, container)
      }
    })
    console.log('DRAG EFFECTS: ready')
```

**Comment by kristianmandrup** [comment]
You are running the `DragEffects` example untouched!? On my environment it works just fine

**Comment by dinogit** [comment]
Modified. I am building kanban board and have dynamic set of states. Inside one state is set of tasks. These tasks are draggable. Basically when task is droped, I need that task properties (model).

**Comment by kristianmandrup** [comment]
I get the same error now. It seemed to work correctly when I had multiple tabs wit the same app running, but when I only had one tab I got the same error.

The problem is here in Service, somehow using the wrong drake to match on I think

```js
  findModelContainerByContainer (container, drake) {
    if (!drake.models) {
      this.log('findModelContainerByContainer', 'warning: no models found')
      return
    }
    let found = drake.models.find(model => model.container === container)
    if (!found) {
      this.log('No matching model could be found for container:', container)
      this.log('... in drake', drake.name, ' models:', drake.models)
    }
    return found 
  }
```

**Comment by kristianmandrup** [comment]
Finally fixed it and published latest on npm.

**Comment by kristianmandrup** [comment]
You are also welcome to try out my new branch [model-manager](https://github.com/kristianmandrup/vue2-dragula/tree/model-manager)

Now you can define a `modelManager` to manage your model, so it can be immutable with undo/redo or whatever you like ;)
