### ISSUE TITLE
how to update array

### ISSUE THREAD

**Issue by height** [kristianmandrup/vue2-dragula-demo#3]

**Comment by kristianmandrup** [comment]
Please see the [draghandler docs](https://github.com/kristianmandrup/vue2-dragula#draghandler-for-fine-grained-control) and [models docs](https://github.com/kristianmandrup/vue2-dragula#binding-models-to-draggable-elements)

You can also [add drake models dynamically](https://github.com/kristianmandrup/vue2-dragula#advanced-drake-configuration) (for more details see dragula docs)
