### ISSUE TITLE
how to update array model

### ISSUE THREAD

**Issue by height** [kristianmandrup/vue2-dragula-demo#4]

**Comment by kristianmandrup** [comment]
I'm not sure exactly what you are asking. I just answered in #3

**Comment by kristianmandrup** [comment]
You are also welcome to try out my new branch with `ModelManager`

[model-manager](https://github.com/kristianmandrup/vue2-dragula/tree/model-manager)

and the demo branch [time-travel](https://github.com/kristianmandrup/vue2-dragula-demo/tree/time-travel) - no UI for time travel yet, but look at `ImmutableModelManager`
