### ISSUE TITLE
Not running with latest vue.js 2

### ISSUE THREAD

**Issue by lbisson** [kristianmandrup/vue2-dragula-demo#6]
cloned the git repo.  
npm install, was missing dependencies.  when I got a clean install npm run dev.  I get a pink home screen that doesn't have anything that works on it other than link to the github page.  No nav bar visible or anything.  Not sure if I am doing something incorrectly or not.

The missing dependency had to do with lint.

**Comment by kristianmandrup** [comment]
Been away on vacation. Will have a look now. Thanks

**Comment by kristianmandrup** [comment]
Looks like a problem related to vue-material

From my browser `console.log`  after updating to latest vue2

```
[Vue warn]: Error when rendering component <md-toolbar>: 
warn
localhost/:3105 Uncaught TypeError: t._h is not a function
```

**Comment by kristianmandrup** [comment]
Updated to use latest vue-material API. Works now :)
